name: Deployment pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        types: ["opened", "synchronize"]

jobs:
    check-for-skip:
        runs-on: ubuntu-latest
        outputs:
            skip: ${{ steps.skip.outputs.skip }}
        steps:
            - uses: actions/checkout@v3
            - id: skip
              env:
                COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
              run: |
                  skip=$(echo "$COMMIT_MESSAGES" | grep -qi "#skip" && echo true || echo false)
                  echo "skip=$skip" >> "$GITHUB_OUTPUT"
    
    pipeline:
        runs-on: ubuntu-latest
        needs: check-for-skip
        steps:
            - uses: actions/checkout@v3
            - uses: creyD/prettier_action@v4.3
              if: github.event_name == 'push'
              with:
                prettier_options: --write **/*.{js,jsx,cjs}
            - uses: actions/setup-node@v3
              with:
                node-version: '20'
            - name: install dependencies
              run: |
                npm ci
                cd client
                npm ci
            - name: create .env
              run: echo "${{ secrets.ENV_FILE }}" > .env
            - name: server unit tests
              run: npm run test
            - name: client unit tests
              run: |
                cd client
                npm run test
            - name: e2e tests
              uses: cypress-io/github-action@v5
              with:
                command: npm --prefix ./client run test:e2e
                start: |
                  npm run start:test
                  npm --prefix ./client run dev
                wait-on: http://localhost:5173
            - name: Deploy to Render
              if: github.event_name == 'push' && needs.check-for-skip.outputs.skip == 'false'
              run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
            - name: Discord notificatoin
              if: ${{ always() && vars.DISCORD_WEBHOOK_ACTIVE == 'true' && (github.event_name == 'push' || job.status != 'success')}}
              uses: sarisia/actions-status-discord@v1.13.0
              with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
                status: ${{ job.status }}
                title: 'Deploy'
                description: 'Test, and deploy to Render'
                url: 'https://bloglist-fso-degenone.onrender.com'
                username: GitHub Actions
                content: 'Action triggered by ${{ github.actor }}'

    tag_releases:
        needs: [pipeline, check-for-skip]
        if: ${{ github.event_name == 'push' && needs.check-for-skip.outputs.skip == 'false' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.67.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: 'patch'
                WITH_V: true
